### ISSUE TITLE
nix: trying to init it 

### ISSUE THREAD

**Issue by s0me1newithhand7s** [dqrk0jeste/owl#3]
```Shell
┏━ 1 Errors: 
┃ error: builder for '/nix/store/57x7a5c1d9m5h5mkv19bf63zdpnx0c86-owl-_git.drv' failed with exit code 2;
┃        last 25 log lines:
┃        >       |              ^
┃        > src/output.c:152:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
┃        >   152 |           && (uint32_t)k->args == workspace->index) {
┃        >       |              ^
┃        > gcc -c src/owl.c -I/nix/store/3jn6qdkamvfjqh3lbw8lcin3y79x96kg-libinput-1.26.2-dev/include -I/nix/store/hridjg9m5dvjmasams0w274qi79q8jp…
┃        > gcc -c src/pointer.c -I/nix/store/3jn6qdkamvfjqh3lbw8lcin3y79x96kg-libinput-1.26.2-dev/include -I/nix/store/hridjg9m5dvjmasams0w274qi79…
┃        > gcc -c src/popup.c -I/nix/store/3jn6qdkamvfjqh3lbw8lcin3y79x96kg-libinput-1.26.2-dev/include -I/nix/store/hridjg9m5dvjmasams0w274qi79q8…
┃        > gcc -c src/rendering.c -I/nix/store/3jn6qdkamvfjqh3lbw8lcin3y79x96kg-libinput-1.26.2-dev/include -I/nix/store/hridjg9m5dvjmasams0w274qi…
┃        > gcc -c src/something.c -I/nix/store/3jn6qdkamvfjqh3lbw8lcin3y79x96kg-libinput-1.26.2-dev/include -I/nix/store/hridjg9m5dvjmasams0w274qi…
┃        > gcc -c src/toplevel.c -I/nix/store/3jn6qdkamvfjqh3lbw8lcin3y79x96kg-libinput-1.26.2-dev/include -I/nix/store/hridjg9m5dvjmasams0w274qi7…
┃        > gcc -c src/workspace.c -I/nix/store/3jn6qdkamvfjqh3lbw8lcin3y79x96kg-libinput-1.26.2-dev/include -I/nix/store/hridjg9m5dvjmasams0w274qi…
┃        > gcc build/config.o build/decoration.o build/ipc.o build/keybinds.o build/keyboard.o build/layer_surface.o build/layout.o build/output.o…
┃        > sudo cp build/owl /usr/local/bin/owl; \
┃        > sudo cp build/owl-ipc /usr/local/bin/owl-ipc; \
┃        > sudo mkdir -p /usr/share/owl; \
┃        > sudo cp default.conf /usr/share/owl/default.conf
┃        > sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
┃        > sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.
┃        > sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
┃        > sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.
┃        > sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
┃        > sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.
┃        > sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
┃        > sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.
┃        > make: *** [Makefile:44: install] Error 1
┃        For full logs, run 'nix log /nix/store/57x7a5c1d9m5h5mkv19bf63zdpnx0c86-owl-_git.drv'.
┣━ Dependency Graph:
┃ ⚠ owl-_git failed with exit code 2 after ⏱ 3s in installPhase
┣━━━                                                     
┗━ ∑ ⚠ Exited after 1 build failures at 01:05:53 after 5s
```

NixOS by default is sandboxed, so may i ask..

### why `sudo`?

**Comment by danihek** [comment]
Look at Makefile - there is sudo [here](https://github.com/dqrk0jeste/owl/blob/dfd98f121058fcc1f2f8122e7e41445f8037c2f6/Makefile)

Well... user should manually add sudo before running ``make``

**Comment by s0me1newithhand7s** [comment]
> Look at Makefile - there is sudo [here](https://github.com/dqrk0jeste/owl/blob/dfd98f121058fcc1f2f8122e7e41445f8037c2f6/Makefile)
> 
> Well... user should manually add sudo before running `make`

i've figured out how to avoid sudo, nvm

**Comment by dqrk0jeste** [comment]
i am not familiar with nixos, so excuse my mistake. what would be the right way to install it on nixos? i will gladly add the support

**Comment by s0me1newithhand7s** [comment]
> i am not familiar with nixos, so excuse my mistake. what would be the right way to install it on nixos? i will gladly add the support

i did some patches but sadly i can't overcome issue with harcoded path, so temporary i've created config in my user dir:
![image](https://github.com/user-attachments/assets/c57696fc-4879-4bcb-86a5-2d05a929bdf2)
i'll try to overcome this.. but yeah, i'm not familiar with C

**Comment by s0me1newithhand7s** [comment]
i'll provide a [gist](https://gist.github.com/s0me1newithhand7s/7e5ae2cabbdddc6994e99defe07e2695)!

**Comment by s0me1newithhand7s** [comment]
hm, seems like sway packaged with [patch](https://github.com/NixOS/nixpkgs/blob/33b9d57c656e65a9c88c5f34e4eb00b83e2b0ca9/pkgs/by-name/sw/sway-unwrapped/load-configuration-from-etc.patch) that fixes it..

**Comment by dqrk0jeste** [comment]
i will take a look and try to provide a solution. would it work to, on nixos, just copy the default config to $XDG_CONFIG_HOME/owl/owl.conf (basically as if you have created it) and skip copying it to /usr/...

**Comment by s0me1newithhand7s** [comment]
> i will take a look and try to provide a solution. would it work to, on nixos, just copy the default config to $XDG_CONFIG_HOME/owl/owl.conf (basically as if you have created it) and skip copying it to /usr/...

it would, but if we can, yk, make it work with stock config out-of-box - that will be so W

**Comment by dqrk0jeste** [comment]
what i meant was to do it programatically in the makefile, instead of copying to the /usr/share/owl to copy it to home config. it is not the ideal solution, but a temporary one until we figure one how to do it the right way.

i will try my best to come by the better solution till the end of the week.

**Comment by danihek** [comment]
Can't you just embed default config into something like ``defaultconfig.h`` and just instead reading a file, include it extern global char* variable?

```
extern char *default_config = " \
env XDG_CURRENT_DESKTOP owl \
env XDG_SESSION_TYPE wayland \
env XDG_SESSION_DESKTOP owl \
\
min_toplevel_size 10 \
\
keyboard_rate 30 \
keyboard_delay 200 \
\
natural_scroll 1 \
tap_to_click 1 \
\
border_width 2 \
outer_gaps 12 \
inner_gaps 6 \
\
master_count 1 \
master_ratio 0.65 \
\
active_border_color 256 256 256 256 \
inactive_border_color 0 0 0 256 \
\
keybind alt escape exit \
\
keybind super t run kitty \
keybind super a run \"rofi -show drun\" \
\
keybind super x resize \
keybind super z move \
\
keybind super k move_focus up  \
keybind super j move_focus down  \
keybind super l move_focus right  \
keybind super h move_focus left  \
\
keybind super+shift k swap up  \
keybind super+shift j swap down  \
keybind super+shift l swap right  \
keybind super+shift h swap left  \
\
keybind super q kill_active  \
keybind super w switch_floating_state ";
```

**Comment by s0me1newithhand7s** [comment]
> Can't you just embed default config into something like `defaultconfig.h` and just instead reading a file, include it, and define extern global char* variable?

point here - we need to copy from **default** config, and not defining it can lead to problems

**Comment by dqrk0jeste** [comment]
sorry for the wait, i did not have a lot of free time these past few days. after a bit of exploring (chatgpt-ing) i think a have found a solution - when loading the config add the check for the env variable OWL_DEFAULT_CONFIG_PATH that can be strapped by default into the binary on nixos like this
```
    wrapProgram $out/bin/owl --set OWL_DEFAULT_CONFIG_PATH "$out/share/default.conf"
```
and if there is no such variable we use the hard-coded one.  also, i wonder if this is a better way to handle the installation directly in the package.nix as it does not add additional complexity to the makefile
```
  buildPhase = ''
    make
  '';

  installPhase = ''
    mkdir -p $out/bin
    mkdir -p $out/share
    cp build/owl $out/bin/
    cp build/owl-ipc $out/bin/
    cp default.conf $out/share/
  '';
```
@s0me1newithhand7s

**Comment by s0me1newithhand7s** [comment]
> sorry for the wait, i did not have a lot of free time these past few days. after a bit of exploring (chatgpt-ing) i think a have found a solution - when loading the config add the check for the env variable OWL_DEFAULT_CONFIG_PATH that can be strapped by default into the binary on nixos like this
> 
> ```
>     wrapProgram $out/bin/owl --set OWL_DEFAULT_CONFIG_PATH "$out/share/default.conf"
> ```
> 
> and if there is no such variable we use the hard-coded one. also, i wonder if this is a better way to handle the installation directly in the package.nix as it does not add additional complexity to the makefile
> 
> ```
>   buildPhase = ''
>     make
>   '';
> 
>   installPhase = ''
>     mkdir -p $out/bin
>     mkdir -p $out/share
>     cp build/owl $out/bin/
>     cp build/owl-ipc $out/bin/
>     cp default.conf $out/share/
>   '';
> ```
> 
> @s0me1newithhand7s

i can certainly do it and test it!

**Comment by dqrk0jeste** [comment]
great, really appreciate it!

**Comment by s0me1newithhand7s** [comment]
i think part with:
> ```
>   buildPhase = ''
>     make
>   '';
> 
>   installPhase = ''
>     mkdir -p $out/bin
>     mkdir -p $out/share
>     cp build/owl $out/bin/
>     cp build/owl-ipc $out/bin/
>     cp default.conf $out/share/
>   '';
> ```
applies only if i will PR it into nixpkgs - but i won't :D

**Comment by s0me1newithhand7s** [comment]
![image](https://github.com/user-attachments/assets/ea47a892-89c3-4a4c-a4d4-4f16f5905874)
hm

**Comment by dqrk0jeste** [comment]
> applies only if i will PR it into nixpkgs - but i won't :D

shouldn't anyone be able to package their apps on nixos regardless of if they are going to be in the public repositories or not? thats usually how it is on other distros. and claude seems to suggest that:

>The key point is that Nix allows direct installation from a package.nix file without requiring submission to any central repository. Users can:
> 
> Clone your repository
> Point Nix directly to the package.nix
> Install the package locally
> 
> This makes sharing Nix packages very flexible - you can distribute them via Git, direct file sharing, or any method that lets someone > access the source code and package definition.

**Comment by s0me1newithhand7s** [comment]
> shouldn't anyone be able to package their apps on nixos regardless of if they are going to be in the public repositories or not? thats usually how it is on other distros. and claude seems to suggest that:


there is a problem with my solution to package `owl` since even `master`'s branch `wlroots` is old - it's not reproducible. `builtins.getFlake` is flake-exclusive system, and since not everyone uses flakes. :D 
i can make it reproducible - just build `-git` version of `wlroots` and create a flake for it, but for now - i need to figure out how to fix issue.

**Comment by s0me1newithhand7s** [comment]
> that seems reasonable because i still have not added the change i was talking about above. have you added the environment variable? you should be able to echo it from the terminal to check if its there

https://gist.github.com/s0me1newithhand7s/3558875e61dcbbbb02fed53b9acdb82f

**Comment by dqrk0jeste** [comment]
thank you, you too! do you want to open a PR here so we can get that package.nix and a envvar check for other people building it on nix?

**Comment by s0me1newithhand7s** [comment]
> thank you, you too! do you want to open a PR here so we can get that package.nix and a envvar check for other people building it on nix?

i'll do a PR to `README.md` with link to a [nyxpkgs](https://github.com/chaotic-cx/nyx) where i init owl :D

**Comment by dqrk0jeste** [comment]
sounds great!

**Comment by s0me1newithhand7s** [comment]
i did it! 
https://github.com/chaotic-cx/nyx/pull/937
